version: "3.9"

services:
  proxy:
    image: nginx
    ports:
      - 8083:80
    volumes:
      - ../ops/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tracks_network
    depends_on:
      - app

  app:
    image: yoandevelop/api-tracks
    build:
      context: .
    command: sh -c 'sleep 10; npm start'
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - dbmongo
    networks:
      - tracks_network

  db:
    image: mysql
    container_name: db-tracks
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - vol_mysql:/var/lib/mysql
    networks:
      - tracks_network

  dbmongo:
    image: mongo
    container_name: db-tracks-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - vol_mongo:/etc/mongo
    networks:
      - tracks_network

volumes:
  vol_mysql:
  vol_mongo:
networks:
  tracks_network:
