apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apitracks
  template:
    metadata:
      labels:
        app: apitracks
    spec:
      containers:
        - name: proxy
          image: nginx
          ports:
          - containerPort: 80
            name: proxy
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "250m"

        - name: apitracks
          image: yoandevelop/api-tracks:v1
          env:
          - name: DB_URI
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: api-tracks
              containerPort: 3000
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: apitracks
  namespace: demo
spec:
  type: NodePort
  selector:
    app: apitracks
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
