apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmongo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: dbmongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dbmongo
    spec:
      containers:
      - name: dbmongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
          name: dbmongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
